n_samples: 500
centers: 2
cluster_std: 5 # was 3.5
random_state: 42

uncertainty_threshold: 0.05 #0.2 worked best -> check ob 0.1 oder 0.11 schritte
# Grafik mit Kurve wie sich modell ver채ndert bei 채ndern des thresholds
# mehrere seeds verwenden (3-5) zum durchprobieren (min linie, standard deviation als range)
# Design entscheidungen erkl채ren 
# zweiten schweren datensatz hinzuf체gen
# erstmal false labeling rauslassen

# checken ob es sinnvol ist einen cap auf die datengenerierung zu tun 